-- =========================================================================
-- SUPABASE SCHEMA INITIALIZATION & MIGRATIONS
-- =========================================================================
-- This file contains the complete database schema, including tables,
-- row-level security (RLS) policies, and RPC functions.
-- Run this in the Supabase SQL editor to recreate the entire project.
-- =========================================================================

-- 1. Enable Extensions
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

-- =========================================================================
-- 2. TABLE DEFINITIONS
-- =========================================================================

-- Groups table
CREATE TABLE IF NOT EXISTS groups (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  created_by TEXT, -- Clerk User ID (Set to NULL on user deletion)
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Group members table
CREATE TABLE IF NOT EXISTS group_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id UUID REFERENCES groups(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL, -- Clerk User ID
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(group_id, user_id)
);

-- Profiles table
CREATE TABLE IF NOT EXISTS profiles (
  user_id TEXT PRIMARY KEY,
  preferred_unit TEXT DEFAULT 'Inches',
  
  -- Measurements
  height TEXT,
  weight TEXT,
  chest TEXT,
  waist TEXT,
  inseam TEXT,
  
  -- Quick sizes
  shoe_size TEXT,
  ring_size TEXT,
  preferred_fit TEXT,
  
  -- Aesthetics
  metal_preference TEXT,
  favorite_brands TEXT,
  dealbreakers TEXT,
  style_words TEXT,
  notes TEXT,
  
  -- Embeddings
  style_embedding vector(768),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Wishes table
CREATE TABLE IF NOT EXISTS wishes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  url TEXT,
  image_url TEXT,
  is_inspo BOOLEAN DEFAULT false,
  user_id TEXT NOT NULL, -- Clerk User ID (The owner)
  group_id UUID REFERENCES groups(id) ON DELETE CASCADE,
  reserved_by TEXT, -- Clerk User ID of the reserver (NULL if available)
  item_embedding vector(768), -- Embeddings
  price NUMERIC(10, 2) -- Target amount for group funding
);

-- Contributions Table (Ledger for fractional gifting)
CREATE TABLE IF NOT EXISTS contributions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wish_id BIGINT REFERENCES wishes(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL, -- Clerk User ID
  amount NUMERIC(10, 2) NOT NULL CHECK (amount > 0),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- =========================================================================
-- 3. ROW LEVEL SECURITY (RLS) POLICIES
-- =========================================================================

-- Enable RLS on all structural tables
ALTER TABLE groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE group_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE wishes ENABLE ROW LEVEL SECURITY;
ALTER TABLE contributions ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------
-- Profiles Policies
-- ---------------------------------------------------------
CREATE POLICY "Allow authenticated to view profiles" ON profiles 
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Users can insert own profile" ON profiles 
  FOR INSERT TO authenticated WITH CHECK (user_id = (auth.jwt() ->> 'sub'));

CREATE POLICY "Users can update own profile" ON profiles 
  FOR UPDATE TO authenticated USING (user_id = (auth.jwt() ->> 'sub'));

-- ---------------------------------------------------------
-- Groups Policies
-- ---------------------------------------------------------
CREATE POLICY "Allow group creation" ON groups 
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow members to view group info" ON groups 
  FOR SELECT TO authenticated USING (
    EXISTS (
      SELECT 1 FROM group_members 
      WHERE group_members.group_id = groups.id 
      AND group_members.user_id = (auth.jwt() ->> 'sub')
    )
  );

-- ---------------------------------------------------------
-- Group Members Policies
-- ---------------------------------------------------------
CREATE POLICY "Allow members to join a group" ON group_members 
  FOR INSERT TO authenticated WITH CHECK (user_id = (auth.jwt() ->> 'sub'));

CREATE POLICY "Allow reading group members" ON group_members 
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow members to view their memberships" ON group_members 
  FOR SELECT TO authenticated USING (user_id = (auth.jwt() ->> 'sub'));

-- ---------------------------------------------------------
-- Wishes Policies
-- ---------------------------------------------------------
-- Allow users to read wishes
CREATE POLICY "Allow users to select wishes" ON wishes 
  FOR SELECT TO authenticated USING (true);

-- Allow users to create wishes
CREATE POLICY "Allow users to insert wishes" ON wishes 
  FOR INSERT TO authenticated WITH CHECK (user_id = (auth.jwt() ->> 'sub'));

-- Allow users to delete their own wishes
CREATE POLICY "Allow users to delete own wishes" ON wishes 
  FOR DELETE TO authenticated USING (user_id = (auth.jwt() ->> 'sub'));

-- Allow group members to update wishes (specifically to lock reservations)
CREATE POLICY "Allow group members to update locks" ON wishes
  FOR UPDATE TO authenticated
  USING (true)
  WITH CHECK (true);

-- ---------------------------------------------------------
-- Contributions Policies
-- ---------------------------------------------------------
-- Allow users to see all contributions for transparency
CREATE POLICY "Allow authenticated to read contributions" ON contributions 
  FOR SELECT TO authenticated USING (true);

-- Allow users to make a contribution
CREATE POLICY "Allow authenticated to insert contributions" ON contributions 
  FOR INSERT TO authenticated WITH CHECK (user_id = (auth.jwt() ->> 'sub'));

-- =========================================================================
-- 4. RPC FUNCTIONS (Stored Procedures)
-- =========================================================================

-- Match wishes RPC
CREATE OR REPLACE FUNCTION match_wishes (
  query_embedding vector(768),
  match_threshold float,
  match_count int,
  p_group_id uuid,
  p_user_id text
)
RETURNS TABLE (
  id bigint,
  name text,
  description text,
  url text,
  is_inspo boolean,
  similarity float
)
LANGUAGE sql
AS $$
  SELECT
    wishes.id,
    wishes.name,
    wishes.description,
    wishes.url,
    wishes.is_inspo,
    1 - (wishes.item_embedding <=> query_embedding) AS similarity
  FROM wishes
  WHERE 1 - (wishes.item_embedding <=> query_embedding) > match_threshold
    AND wishes.group_id = p_group_id
    AND wishes.user_id = p_user_id
  ORDER BY wishes.item_embedding <=> query_embedding
  LIMIT match_count;
$$;

-- Reservation RPC
CREATE OR REPLACE FUNCTION reserve_wish_atomic(p_wish_id bigint, p_user_id text)
RETURNS wishes AS $$
DECLARE
  result wishes;
BEGIN
  UPDATE wishes
  SET reserved_by = p_user_id
  WHERE id = p_wish_id AND reserved_by IS NULL
  RETURNING * INTO result;
  
  IF NOT FOUND THEN
    RAISE EXCEPTION 'ALREADY_RESERVED';
  END IF;
  
  RETURN result;
END;
$$ LANGUAGE plpgsql;

-- Contribute to Wish RPC (Atomic Ledger Transaction)
CREATE OR REPLACE FUNCTION contribute_to_wish(p_wish_id bigint, p_user_id text, p_amount numeric)
RETURNS json AS $$
DECLARE
  v_wish wishes;
  v_current_total numeric;
  v_new_total numeric;
BEGIN
  -- Lock the specific wish row for update to prevent race conditions
  SELECT * INTO v_wish FROM wishes WHERE id = p_wish_id FOR UPDATE;
  
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Wish not found';
  END IF;

  IF v_wish.price IS NULL THEN
    RAISE EXCEPTION 'Cannot contribute to an item without a price';
  END IF;

  IF v_wish.reserved_by IS NOT NULL THEN
    RAISE EXCEPTION 'Item is already fully reserved or funded';
  END IF;

  -- Calculate current total contributions
  SELECT COALESCE(SUM(amount), 0) INTO v_current_total 
  FROM contributions 
  WHERE wish_id = p_wish_id;

  v_new_total := v_current_total + p_amount;

  -- Check if contribution exceeds price
  IF v_new_total > v_wish.price THEN
    RAISE EXCEPTION 'Contribution exceeds the target price. Remaining amount needed: %', (v_wish.price - v_current_total);
  END IF;

  -- Insert contribution
  INSERT INTO contributions (wish_id, user_id, amount)
  VALUES (p_wish_id, p_user_id, p_amount);

  -- If fully funded, lock the wish
  IF v_new_total = v_wish.price THEN
    UPDATE wishes SET reserved_by = 'GROUP_FUNDED' WHERE id = p_wish_id;
    v_wish.reserved_by := 'GROUP_FUNDED';
  END IF;

  -- Return updated status
  RETURN json_build_object(
    'new_total', v_new_total,
    'price', v_wish.price,
    'is_funded', (v_new_total = v_wish.price)
  );
END;
$$ LANGUAGE plpgsql;

-- User data deletion RPC
CREATE OR REPLACE FUNCTION delete_user_data(p_user_id text)
RETURNS void AS $$
BEGIN
  DELETE FROM wishes WHERE user_id = p_user_id;
  DELETE FROM group_members WHERE user_id = p_user_id;
  DELETE FROM profiles WHERE user_id = p_user_id;
  -- Nullify creator for user-created groups
  UPDATE groups SET created_by = NULL WHERE created_by = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Cascade Group Deletion RPC
CREATE OR REPLACE FUNCTION delete_group_data(p_group_id uuid)
RETURNS void AS $$
BEGIN
  DELETE FROM wishes WHERE group_id = p_group_id;
  DELETE FROM group_members WHERE group_id = p_group_id;
  DELETE FROM groups WHERE id = p_group_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =========================================================================
-- 5. REALTIME SYNC PUBLICATION
-- =========================================================================
-- Enable Realtime for wishes table
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND tablename = 'wishes'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE wishes;
  END IF;
  
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND tablename = 'contributions'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE contributions;
  END IF;
END $$;
