"use server";

import { auth } from "@clerk/nextjs/server";
import { createClient } from "@supabase/supabase-js";

// Builds a secure, authenticated Supabase connection for each request
async function getAuthedSupabaseClient() {
  const { getToken } = await auth();
  
  // Grab the custom JWT token specifically generated by Clerk for Supabase
  const token = await getToken({ template: "supabase" });

  console.log("🎟️ CLERK TOKEN STATUS:", token ? "Token acquired successfully! ✅" : "TOKEN IS NULL! ❌");

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
  const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

  // Inject the Clerk token directly into the Authorization headers
  return createClient(supabaseUrl, supabaseAnonKey, {
    global: {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    },
  });
}

// Securely grabs the user's active group ID
async function getUserGroupId(supabaseClient: any, userId: string) {
  const { data, error } = await supabaseClient
    .from("group_members")
    .select("group_id")
    .eq("user_id", userId)
    .single();

  if (error || !data) throw new Error("User does not belong to any group.");
  return data.group_id;
}

// Securely fetch all wishes inside the user's shared group space
export async function getWishesFromDatabase() {
  const { userId } = await auth();
  if (!userId) return [];

  try {
    const supabase = await getAuthedSupabaseClient();
    const groupId = await getUserGroupId(supabase, userId);

    const { data, error } = await supabase
      .from("wishes")
      .select("*")
      .eq("group_id", groupId)
      .order("created_at", { ascending: false });

    if (error) throw error;
    return data;
  } catch (err) {
    console.error("Fetch Security Error:", err);
    return [];
  }
}

// Securely add a wish to the user's shared group space
export async function addWishToDatabase(name: string, isInspo: boolean, description: string, url: string) {
  const { userId } = await auth();
  if (!userId) throw new Error("Unauthorized");

  try {
    const supabase = await getAuthedSupabaseClient();
    const groupId = await getUserGroupId(supabase, userId);

    const { data, error } = await supabase
      .from("wishes")
      .insert([
        {
          name,
          description: description || null,
          url: url || null,
          is_inspo: isInspo,
          user_id: userId,
          group_id: groupId,
        },
      ])
      .select()
      .single();

    if (error) throw error;
    return data;
  } catch (err) {
    throw new Error("Failed to save to database");
  }
}

// Securely delete a wish from the database (Only if it belongs to you!)
export async function deleteWishFromDatabase(id: number) {
  const { userId } = await auth();
  if (!userId) throw new Error("Unauthorized");

  try {
    const supabase = await getAuthedSupabaseClient();
    
    // Ensure the item matches the ID and enforces that the creator's user_id matches the logged-in user
    const { error } = await supabase
      .from("wishes")
      .delete()
      .eq("id", id)
      .eq("user_id", userId);

    if (error) throw error;
  } catch (err) {
    console.error("Delete Security Error:", err);
    throw new Error("Failed to delete from database");
  }
}

// Check if the logged-in user belongs to a group yet
export async function checkUserGroup() {
  const { userId } = await auth();
  if (!userId) return null;

  try {
    const supabase = await getAuthedSupabaseClient();
    const { data, error } = await supabase
      .from("group_members")
      .select("group_id, groups(name)")
      .eq("user_id", userId)
      .maybeSingle(); 

    if (error || !data) return null;
    
    return { 
      groupId: data.group_id, 
      groupName: (data.groups as any)?.name || "Our Shared List" 
    };
  } catch {
    return null;
  }
}

// Create a brand new group and automatically link the creator to it
export async function createGroup(groupName: string) {
  const { userId } = await auth();
  if (!userId) throw new Error("Unauthorized");

  const supabase = await getAuthedSupabaseClient();

  const { data: group, error: groupError } = await supabase
    .from("groups")
    .insert([{ name: groupName }])
    .select()
    .single();

  if (groupError) {
    console.error("DB SCHEMA ERROR:", groupError);
    throw new Error(`Database rejected: ${groupError.message} (${groupError.details || 'No details'})`);
  }

  const { error: memberError } = await supabase
    .from("group_members")
    .insert([{ group_id: group.id, user_id: userId }]);

  if (memberError) throw new Error("Failed to link user to the new group.");

  return { groupId: group.id, groupName: group.name };
}

// Join an existing group tenant 
export async function joinGroup(groupId: string) {
  const { userId } = await auth();
  if (!userId) throw new Error("Unauthorized");

  const supabase = await getAuthedSupabaseClient();

  const { error } = await supabase
    .from("group_members")
    .insert([{ group_id: groupId, user_id: userId }]);

  if (error) {
    throw new Error("Invalid Join Code or you are already a member.");
  }

  const { data: group } = await supabase
    .from("groups")
    .select("name")
    .eq("id", groupId)
    .single();

  return { groupId, groupName: group?.name || "Shared List" };
}